<?php

require('fpdf.php');
include('digtoword.php');
include('../qrcode/phpqrcode/qrlib.php');

ob_start();
header("Content-Encoding: None", true);

$conn = mysqli_connect("localhost:3307", "root", "", "pdfdemo");

if(!$conn)
{
    die("Connection Failed");
}

$id = isset($_GET['id']) ? $_GET['id'] : '';

$sql = "SELECT * FROM receipt WHERE rno = ?";

$stmt = mysqli_prepare($conn, $sql);
mysqli_stmt_bind_param($stmt, "s", $id);
mysqli_stmt_execute($stmt);

$result = mysqli_stmt_get_result($stmt);
$row = mysqli_fetch_assoc($result);

if(!$row)
{
    die("Receipt Not Found");
}

$word = ucwords(numberTowords($row['amt'])) . " Only";

//$qr_url = "http://localhost/2026/pdf/view.php?id=" . $row['stud_id'];
$qr_url = "http://192.168.1.65/2026/pdf/view.php?id=" . $row['stud_id'];

if(!is_dir('qr'))
{
    mkdir('qr');
}

$qr_file = __DIR__ . "/qr/receipt_" . $row['stud_id'] . ".png";

QRcode::png($qr_url, $qr_file, QR_ECLEVEL_L, 4);

$pdf = new FPDF('P','mm','A4');

$pdf->AddPage();

$pdf->Image('title.jpg', 10, 12, 55, 12);
$pdf->Image('logo.png', 115, 11, 22, 22);
$pdf->Image('sign.jpg', 154, 75, 40, 17);

$pdf->SetFont('Arial','',8);

$pdf->Cell(130, 3, 'Managed by Madhav Education & Charitable Trust', 0, 0);
$pdf->Cell(59, 3, '', 0, 1);

$pdf->SetFont('Arial','B',14);

$pdf->Cell(130, 5, '', 0, 0);
$pdf->Cell(59, 5, 'RECEIPT', 0, 1);

$pdf->SetFont('Arial','',10);

$pdf->Cell(130, 5, 'Porbandar, Gujarat', 0, 0);
$pdf->Cell(25, 5, 'Date', 0, 0);
$pdf->Cell(34, 5, $row['rdate'], 0, 1);

$pdf->Cell(130, 5, 'Contact: 9033392721', 0, 0);
$pdf->Cell(25, 5, 'Receipt #', 0, 0);
$pdf->Cell(34, 5, $row['rno'], 0, 1);

$pdf->Cell(130, 5, 'Email: miwtindia@gmail.com', 0, 0);
$pdf->Cell(25, 5, '', 0, 0);
$pdf->Cell(34, 5, '', 0, 1);

$pdf->Cell(189, 10, '', 0, 1);

$pdf->SetFont('Arial','',11);

$pdf->Cell(50, 5, 'Received with thanks from', 0, 0);

$pdf->SetFont('Arial','B',11);

$pdf->Cell(139, 5, $row['stud_nm'], 1, 1);

$pdf->Cell(189, 3, '', 0, 1);

$pdf->SetFont('Arial','',11);

$pdf->Cell(36, 5, 'Rupees (in words)', 0, 0);
$pdf->Cell(153, 5, $word, 1, 1);

$pdf->Cell(189, 3, '', 0, 1);

$pdf->Cell(7, 5, 'by', 0, 0);
$pdf->Cell(42, 5, $row['course'], 1, 0);
$pdf->Cell(21, 5, 'of Course', 0, 0);
$pdf->Cell(119, 5, $row['cname'], 1, 1);

$pdf->Cell(189, 10, '', 0, 1);

$pdf->SetFont('Arial','B',12);

$pdf->Cell(9, 5, 'Rs.', 0, 0);
$pdf->Cell(30, 5, $row['amt'], 1, 0);
$pdf->Cell(110, 5, '', 0, 0);

$pdf->SetFont('Arial','',11);

$pdf->Cell(40, 5, 'Autho. Signatory', 0, 1);

$pdf->Ln(15);

$pdf->SetFont('Arial','B',9);

$pdf->Cell(120, 5, 'e-Receipt generated by Online Student Portal', 0, 0);

if(file_exists($qr_file))
{
    $pdf->Image($qr_file, 100, 80, 25, 25);
}
else
{
    die("QR File Not Found");
}

mysqli_stmt_close($stmt);
mysqli_close($conn);

ob_end_clean();

$pdf->Output();
?>

